version: '2'


services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    container_name: procrustus_es
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true
    ports:
      - 9200:9200
    volumes:
      - ga_es:/usr/share/elasticsearch/data


  pyservice:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ga_service
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - /home/robz/:/home